setw -g mode-keys vi

#keep current path when splitting or opening windows
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
#start windows and panes from 4, not 0
set -g base-index 4
setw -g pane-base-index 4

#highlight active panel
setw -g pane-active-border-style fg=black,bg=green
set -g pane-border-indicators arrows

#copy to system clipboard
if-shell '[ "$XDG_SESSION_TYPE" = "wayland" ]' \
'set -g copy-command "wl-copy"' \
'set -g copy-command "xclip -sel clip -i"'

bind r \
	source-file ~/.tmux.conf \; \
	display-message "Config reloaded"

set -g window-status-current-style bg=black,fg=green

# format date
set -g status-right "%d %b %R"

# activity notification
set -w -g monitor-activity on
set -w -g visual-activity on
set -w -g window-status-activity-style bg=yellow


set -g history-limit 50000

#status line message time
set -g display-time 4000

# faster nvim edit mode ->  command mode
set -s escape-time 10
